/**
 * Provider catalog data — extracted from providers.ts (god-file decomposition).
 * Pure data literal; re-exported by the providers.ts barrel. No behavior change.
 */
export const AUDIO_ONLY_PROVIDERS = {
  deepgram: {
    id: "deepgram",
    serviceKinds: [],
    alias: "dg",
    name: "Deepgram",
    icon: "mic",
    color: "#13EF93",
    textIcon: "DG",
    website: "https://deepgram.com",
  },
  assemblyai: {
    id: "assemblyai",
    serviceKinds: [],
    alias: "aai",
    name: "AssemblyAI",
    icon: "record_voice_over",
    color: "#0062FF",
    textIcon: "AA",
    website: "https://assemblyai.com",
  },
  soniox: {
    id: "soniox",
    serviceKinds: [],
    alias: "sx",
    name: "Soniox",
    icon: "mic",
    color: "#5B5BD6",
    textIcon: "SX",
    website: "https://soniox.com",
  },
  elevenlabs: {
    id: "elevenlabs",
    serviceKinds: [],
    alias: "el",
    name: "ElevenLabs",
    icon: "record_voice_over",
    color: "#6C47FF",
    textIcon: "EL",
    website: "https://elevenlabs.io",
  },
  cartesia: {
    id: "cartesia",
    serviceKinds: [],
    alias: "cartesia",
    name: "Cartesia",
    icon: "spatial_audio",
    color: "#FF4F8B",
    textIcon: "CA",
    website: "https://cartesia.ai",
  },
  fishaudio: {
    id: "fishaudio",
    serviceKinds: [],
    alias: "fishaudio",
    name: "Fish Audio",
    icon: "graphic_eq",
    color: "#3B82F6",
    textIcon: "FA",
    website: "https://fish.audio",
  },
  playht: {
    id: "playht",
    serviceKinds: [],
    alias: "playht",
    name: "PlayHT",
    icon: "play_circle",
    color: "#00B4D8",
    textIcon: "PH",
    website: "https://play.ht",
  },
  inworld: {
    id: "inworld",
    serviceKinds: [],
    alias: "inworld",
    name: "Inworld",
    icon: "voice_chat",
    color: "#7B2EF2",
    textIcon: "IW",
    website: "https://inworld.ai",
  },
  "aws-polly": {
    id: "aws-polly",
    serviceKinds: [],
    alias: "polly",
    name: "AWS Polly",
    icon: "record_voice_over",
    color: "#FF9900",
    textIcon: "PL",
    website: "https://aws.amazon.com/polly/",
    authHint:
      "Use AWS Secret Access Key as API key; set providerSpecificData.accessKeyId and optional region.",
  },
  gladia: {
    id: "gladia",
    serviceKinds: [],
    alias: "gladia",
    name: "Gladia",
    icon: "record_voice_over",
    color: "#6425FE",
    textIcon: "GL",
    website: "https://gladia.io",
  },

  "rev-ai": {
    id: "rev-ai",
    serviceKinds: [],
    alias: "revai",
    name: "Rev AI",
    icon: "record_voice_over",
    color: "#FF5C35",
    textIcon: "RV",
    website: "https://www.rev.ai",
  },

  speechmatics: {
    id: "speechmatics",
    serviceKinds: [],
    alias: "sm",
    name: "Speechmatics",
    icon: "record_voice_over",
    color: "#0A2540",
    textIcon: "SM",
    website: "https://www.speechmatics.com",
    hasFree: true,
    freeNote: "Free tier — 8 hours/month, no credit card required. Batch (async) mode only.",
  },
};
