/**
 * Provider catalog data — extracted from providers.ts (god-file decomposition).
 * Pure data literal; re-exported by the providers.ts barrel. No behavior change.
 */
export const SEARCH_PROVIDERS = {
  "perplexity-search": {
    id: "perplexity-search",
    serviceKinds: ["webSearch"],
    alias: "pplx-search",
    name: "Perplexity Search",
    icon: "search",
    color: "#20808D",
    textIcon: "PS",
    website: "https://docs.perplexity.ai/guides/search-quickstart",
    authHint: "Same API key as Perplexity (pplx-...)",
  },
  "serper-search": {
    id: "serper-search",
    alias: "serper-search",
    name: "Serper Search",
    icon: "search",
    color: "#4285F4",
    textIcon: "SP",
    website: "https://serper.dev",
    hasFree: true,
    authHint: "API key from serper.dev dashboard",
    serviceKinds: ["webSearch"],
  },
  "brave-search": {
    id: "brave-search",
    serviceKinds: ["webSearch"],
    alias: "brave-search",
    name: "Brave Search",
    icon: "travel_explore",
    color: "#FB542B",
    textIcon: "BR",
    website: "https://brave.com/search/api",
    hasFree: false,
    authHint: "Subscription token from Brave Search API dashboard",
  },
  "exa-search": {
    id: "exa-search",
    alias: "exa-search",
    name: "Exa Search",
    icon: "neurology",
    color: "#1E40AF",
    textIcon: "EX",
    website: "https://exa.ai",
    hasFree: true,
    authHint: "API key from dashboard.exa.ai",
    serviceKinds: ["webSearch", "webFetch"],
  },
  "tavily-search": {
    id: "tavily-search",
    alias: "tavily-search",
    name: "Tavily Search",
    icon: "manage_search",
    color: "#5B4FDB",
    textIcon: "TV",
    website: "https://tavily.com",
    hasFree: true,
    authHint: "API key from app.tavily.com (format: tvly-...)",
    serviceKinds: ["webSearch", "webFetch"],
  },
  "anysearch-search": {
    id: "anysearch-search",
    alias: "anysearch",
    name: "AnySearch",
    icon: "travel_explore",
    color: "#0D9488",
    textIcon: "AS",
    website: "https://anysearch.com",
    hasFree: true,
    authHint:
      "Optional API key from anysearch.com (as_sk_...) - free 1000/day; keyless tier has lower limits",
    serviceKinds: ["webSearch", "webFetch"],
  },
  firecrawl: {
    id: "firecrawl",
    alias: "fc",
    name: "Firecrawl",
    icon: "language",
    color: "#FB923C",
    textIcon: "FC",
    website: "https://firecrawl.dev",
    hasFree: true,
    authHint:
      "API key from firecrawl.dev/app/api-keys (or set your self-hosted Firecrawl base URL)",
    notice: {
      text: "Free tier: 1,000 credits/month. Powers /v1/web/fetch and /v1/search.",
      apiKeyUrl: "https://firecrawl.dev/app/api-keys",
    },
    serviceKinds: ["webSearch", "webFetch"],
  },
  "google-pse-search": {
    id: "google-pse-search",
    serviceKinds: ["webSearch"],
    alias: "google-pse",
    name: "Google Programmable Search",
    icon: "travel_explore",
    color: "#4285F4",
    textIcon: "GP",
    website: "https://developers.google.com/custom-search/v1/overview",
    authHint: "Requires a Google API key and your Programmable Search Engine ID (cx)",
  },
  "nimble-search": {
    id: "nimble-search",
    alias: "nimble",
    name: "Nimble Search",
    icon: "travel_explore",
    color: "#6D28D9",
    textIcon: "NB",
    website: "https://docs.nimbleway.com/nimble-sdk/web-tools/search",
    authHint: "Bearer API key from the Nimble dashboard",
    serviceKinds: ["webSearch", "webFetch"],
  },
  "linkup-search": {
    id: "linkup-search",
    serviceKinds: ["webSearch"],
    alias: "linkup",
    name: "Linkup Search",
    icon: "public",
    color: "#0F766E",
    textIcon: "LU",
    website: "https://docs.linkup.so",
    authHint: "Bearer API key from the Linkup dashboard",
  },
  "searchapi-search": {
    id: "searchapi-search",
    serviceKinds: ["webSearch"],
    alias: "searchapi",
    name: "SearchAPI",
    icon: "manage_search",
    color: "#2563EB",
    textIcon: "SA",
    website: "https://www.searchapi.io/docs/google",
    authHint: "API key from SearchAPI (query param or Bearer auth)",
  },
  "youcom-search": {
    id: "youcom-search",
    serviceKinds: ["webSearch"],
    alias: "youcom-search",
    name: "You.com Search",
    icon: "travel_explore",
    color: "#2563EB",
    textIcon: "YOU",
    website: "https://you.com/business/api/",
    authHint: "X-API-Key from the You.com platform dashboard",
  },
  "searxng-search": {
    id: "searxng-search",
    serviceKinds: ["webSearch"],
    alias: "searxng",
    name: "SearXNG Search",
    icon: "search",
    color: "#1A237E",
    textIcon: "SX",
    website: "https://docs.searxng.org",
    hasFree: true,
    authHint:
      "API key is optional. Set your SearXNG base URL. Some instances may require a bearer token for access.",
  },
  "x-search": {
    id: "x-search",
    alias: "x_search",
    name: "X Search (Grok)",
    icon: "tag",
    color: "#000000",
    textIcon: "X",
    website: "https://docs.x.ai/developers/tools/x-search",
    authHint:
      "SuperGrok OAuth (xai-oauth) or xAI API key. This is Grok X Search, not the X Developer MCP.",
    serviceKinds: ["webSearch"],
  },
  "xquik-search": {
    id: "xquik-search",
    alias: "xquik",
    name: "Xquik X Search",
    icon: "tag",
    color: "#111827",
    textIcon: "XQ",
    website: "https://docs.xquik.com",
    authHint:
      "Xquik API key (xq_...). Search is metered per returned post; the catalog estimate uses 5 results.",
    serviceKinds: ["webSearch"],
  },
  "ollama-search": {
    id: "ollama-search",
    serviceKinds: ["webSearch"],
    alias: "ollama-search",
    name: "Ollama Search",
    icon: "search",
    color: "#58A6FF",
    textIcon: "OS",
    website: "https://ollama.com/settings/keys",
    authHint: "Same API key as Ollama Cloud (from ollama.com/settings/keys)",
  },
  context7: {
    id: "context7",
    alias: "context7",
    name: "Context7 (library docs)",
    icon: "menu_book",
    color: "#6B4FBB",
    textIcon: "C7",
    website: "https://context7.com",
    hasFree: true,
    authHint:
      "API key optional (ctx7sk-...) — anonymous tier works without a key; a key raises the rate limit",
    serviceKinds: ["webSearch", "webFetch"],
  },
};
